apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  replicas: 3   # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest   # Use the latest version of the Nginx image
        ports:
        - containerPort: 80  # Assuming the Nginx container exposes port 80
        resources:
          requests:
            memory: "64Mi"  # Adjust memory request as needed
            cpu: "250m"     # Adjust CPU request as needed