.PHONY: build run functional-test lint

build:
	@mkdir -p bin
	go build -o bin/ ./cmd

run:
	go run ./cmd/main.go

functional-test:
	go run ./functional_test/dummy_main.go

lint:
	@which golangci-lint || { echo "golangci-lint is not installed"; exit 1; }
	golangci-lint run --config golangci-lint.yaml ./...
